### ISSUE TITLE
Evaluar plugins/frameworsk para tablas

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#16]
Buenas tardes,

Te dejo una opción para poder mostrar tablas en web y que puede ser de utilidad en tu TFG: https://datatables.net/

No obstante, es interesante que busques alguna otra alternativa para que las compares y uses la que mejor te _encaje_/_cuadre_ en tu proyecto.

Saludos,

**Comment by idg0015** [comment]
Perfecto! Le echo un ojo y busco alguna alternativa.
