### ISSUE TITLE
Creación diagrama entidad-relación

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#2]
Boceto del diagrama entidad-relación de la aplicación

**Comment by alvarag** [comment]
Versión inicial de requisitos

 -   crear mantenimiento de una tabla de Centros: cada centro tiene 
      -  Id interno del centro  
      -  Nombre del centro 
      -  Abreviatura del centro 
      -  Email del administrativo
(crear los centros de la UBu, separando en 2 centros la EPS )
-    crear mantenimiento de una tabla de Grados/Master: cada título tiene
      -  Id interno del grado/master 
      -  Nombre del grado/master 
      -  Abreviatura del grado/master 
      -  Id del Centro al que está adscrito 
(crear mantenimiento de una tabla de Asignaturas: cada asignatura tiene)
      -  Id interno de la asignatura 
      -  Nombre de la asignatura 
      -  Abreviaturas de la asignatura (*este dato puede ser en función del contexto) 
      -  Id del grado/master al que está adscrito 
      -  Curso 
      -  Semestre (anual, semestre 1, semestre 2, semestre 1 o 2) 
      -  Créditos/horas de teoría del área 
      -  Créditos/horas de prácticas del área 
-    Mantenimiento de Grupos de cada asignatura: para cada asignatura
      -  Curso académico 
      -  Id interno de la asignatura 
      -  número de alumnos matriculados ese curso (* este dato puede cambiar con el tiempo) 
      -  número de grupos teóricos previstos por modalidad 
      -  número de grupos prácticos previstos por modalidad 
      -  identificadores de los grupos y tipo de cada uno de ellos 
-    Mantenimiento de una tabla de Docentes
      -  id del docente 
      -  Nombre docente 
      -  Apellidos del docente 
      -  Email del docente 
      -  Opcional*: 
      -      Nº de RPT * 
      -      Fecha de incorporación* 
      -      Fecha de cese * 
      -      Nº de concurso de contratación* 
      -  Capacidad docente anual (horas/etcs) 
-    Mantenimiento de una asignaciones
      -  Asignar horas a un docente en un grupo un curso (por defecto todo lo pendiente) 
    Vistas de lo asignado a un docente/a una asignatura/a un curso de un título/a todo un título

**Comment by idg0015** [comment]
De momento he sacado el siguiente diagrama entidad-relación:
![Diagrama E-R (1)](https://user-images.githubusercontent.com/74196389/222389772-09e96657-90b7-4510-ac98-6a6d773dadb7.jpg)


Tengo algunas dudas:

1. En la reunión se habló de las entidades área y departamento diciendo que un profesor pertenece a un área de un departamento. ¿Debería tenerlo en cuenta como entidades o es información que no va a ser necesario almacenar?
2. ¿Un grado/master sólo se imparte en un centro o puede ser impartido en más de un centro?
3. En la relación de Docente y Grupo, ¿un docente puede dar clase a varios grupos y un grupo puede ser impartido por varios docentes? Así es como lo he pensado, pero no se si será esa la idea.

**Comment by alvarag** [comment]
Te respondo las cuestiones planteadas:
- Sí, un profesor está en un área y un área está en un dpto. Son entidades propias, puedes ver dptos y áreas en la página web de investigadores de la UBU, ej yo: https://investigacion.ubu.es/investigadores/34986/detalle
- Interesante, un grado/máster podría impartirse en más de un centro pero creo que vamos a simplificarlo a uno de momento.
- Sí un profesor puede dar clase a más de un grupo en una asingnatura e incluso un grupo puede recibir a más de un profesor (porque se repartan la asignatura o cosas por el estilo)

**Comment by carlospardoaguilar** [comment]
Hola


  *   Un grado/máster podría impartirse en más de un centro
pero solo hay un centro al que se adscribe, que es en el que se matricula y es responsable de su expediente.


  *   Lo que has hecho no es el modelo Entidad-Relación es el modelo relacional.
En el modelo Entidad-Relación no se detallan las claves ajenas.
Y posiblemente deberían aparecer más entidades que no dan lugar a tablas.

  *   Debes dar una vuelta como has diseñado lo de los grupos




Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: Álvar Arnaiz-González ***@***.***>
Enviado: sábado, 4 de marzo de 2023 20:00
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Creación diagrama entidad-relación (Issue #2)


Te respondo las cuestiones planteadas:

  *   Sí, un profesor está en un área y un área está en un dpto. Son entidades propias, puedes ver dptos y áreas en la página web de investigadores de la UBU, ej yo: https://investigacion.ubu.es/investigadores/34986/detalle
  *   Interesante, un grado/máster podría impartirse en más de un centro pero creo que vamos a simplificarlo a uno de momento.
  *   Sí un profesor puede dar clase a más de un grupo en una asingnatura e incluso un grupo puede recibir a más de un profesor (porque se repartan la asignatura o cosas por el estilo)

**Comment by alvarag** [comment]
Más comentarios adicionales:

- Quitar las flechas, en el diagrama E/R no tiene mucho sentido. 
- Creo que la relación 1:N de centr/grado está mal. Un centro tiene varios grados/másteres y un master como ha dicho Pardo solo está adscrito a un centro.
- Centro - Master, la relación sería mejor: adscrito
- En las relaciones Grado-Asignatura, Asignatura-Grupo y Grupo-Docente son todas ternarias con Año ya que puede cambiar. Esa tabla Año solo tiene un campo que es año y al pasar a relacional pues veremos que seguramente desaparezca esa tabla (o no).
- Una asingatura tiene grupos de 1 a N. Un grupo solo pertenece a una asingatura si queremos.
- Hay campos, como por ejemplo curso en Curso que ahora no tieneque estar (es una clave ajena). Vendrá luego al hacer el relacional, pero de momento en el E/R solo se ponen los atributos propios de las entidades.
- En Curso no veo lo de grupos teóricos y prácticos...
- En docente tenemos la capacidad anual (que vendrá determinada por el tipo de contrato) y las reducciones.
- Crearía una nueva tabla que sea Contrato (con campos como capacidad anual y que un docente se relacione con esa tabla. Un docente tiene un contrato y con eso ya sabes su capacidad anual (así la quitas de docente), las reducciones sí que son propias del docente y puede ser un número entero.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by idg0015** [comment]
Perfecto. Las claves ajenas las había puesto sin darme cuenta ya que había copiado los campos de arriba.
He hecho varios cambios, pero hay cosas que no me quedan claras.

![Diagrama E-R 2](https://user-images.githubusercontent.com/74196389/222990745-0750cbe0-f233-4b46-b980-0f42b63879a4.jpg)

- Tengo dudas en como se encuentran relacionados los cursos, las asignaturas y los grupos. Lo he puesto como más o menos lo he entendido, pero creo que no está del todo correcto.

- También he visto que el número de grupos teóricos y prácticos previstos se diferencian por modalidad. ¿La modalidad sería una nueva entidad relacionada con Curso o se podría poner como un campo dentro de Curso?

**Comment by alvarag** [comment]
Me gusta más, aún así comentarios:
- En realidad la relación cursos-grupos va con una única relación a año (que en verdad más que año sería curso académico para todos los casos). Entonces, los atributos uqe has puesto en curso lso mueves a curso académico y listo
- Las cardinalidades de esta y pertenece en area-dpto creo están al revés: un dpto tiene muchas áreas (un área a un solo dpto), un área muchos profesores (un profesor sólo un área).
- Grupo no tiene número alumnos, ya lo tienes en la relación.
- Lo de número RPT y concurso Carlos nos dará más luz, no tengo muy claro cómo vamos a ponerlo.
- Como la asignatura puede ser semestral o anual, el campo semestre podría ser Tipo con: A anual, 1 semestre 1º y 2 semestre 2º... o algo así

**Comment by carlospardoaguilar** [comment]
Hola
  creo que en lugar de intentar hacer primero el modelo E-R entero es mejor hacer
los casos de uso y hacer el subconjunto del modelo E-R de cada caso de uso
  y luego fusionarlos en el E-R entero,

Los casos de uso de grupos tiene que analizarse con cuidado, creo que el modelo que presentas no resuelve por completo el problema

Sobre la RPT aunque sea más sencillo pasa un poco lo mismo, mira el caso de uso antes de cerrar la solución



Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: Álvar Arnaiz-González ***@***.***>
Enviado: lunes, 6 de marzo de 2023 9:56
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Cc: CARLOS PARDO AGUILAR ***@***.***>; Comment ***@***.***>
Asunto: Re: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Creación diagrama entidad-relación (Issue #2)


Me gusta más, aún así comentarios:

  *   En realidad la relación cursos-grupos va con una única relación a año (que en verdad más que año sería curso académico para todos los casos). Entonces, los atributos uqe has puesto en curso lso mueves a curso académico y listo
  *   Las cardinalidades de esta y pertenece en area-dpto creo están al revés: un dpto tiene muchas áreas (un área a un solo dpto), un área muchos profesores (un profesor sólo un área).
  *   Grupo no tiene número alumnos, ya lo tienes en la relación.
  *   Lo de número RPT y concurso Carlos nos dará más luz, no tengo muy claro cómo vamos a ponerlo.
  *   Como la asignatura puede ser semestral o anual, el campo semestre podría ser Tipo con: A anual, 1 semestre 1º y 2 semestre 2º... o algo así

**Comment by alvarag** [comment]
Lo que pasa es que para el caso de uso vamos a tener que definirle más los escenarios, que él no tiene en la cabeza cómo son los procesos, lo que es la RPT, etc. Deja un poco más rematado el diagrama E/R y esta semana en la reunión comentamosmás. Por cierto, tenemos fecha para dicha ruenión semanal?

**Comment by idg0015** [comment]
De acuerdo, prefiero verlo primero en la reunión porque hay varias cosas que no termino de entender como funcionan. En cuanto haga los cambios lo subo.
Para la reunión dijimos la semana pasada que en principio el martes a las 9:30.

**Comment by alvarag** [comment]
Prográmala periódica en teams y nos invitas, que sino ubicamos otras reuniones en ese hueco sin darnos cuenta. Saludos,

**Comment by idg0015** [comment]
![Diagrama E-R 3](https://user-images.githubusercontent.com/74196389/223092698-c93f22b5-f0a1-4968-bd6d-43cc324e35df.jpg)

**Comment by idg0015** [comment]
Estoy utilizando esta web: https://app.diagrams.net/

![Diagrama E-R 4](https://user-images.githubusercontent.com/74196389/223096184-d234955e-6108-4bb6-856f-2475b34d2d68.jpg)

**Comment by idg0015** [comment]
Añado el diagrama E/R en limpio de lo visto en la reunión:
![Diagrama E-R Bien](https://user-images.githubusercontent.com/74196389/223988117-76ebec57-ced9-44a3-a326-4d930b9021e5.jpg)
No sé si las cardinalidades en las agregaciones están bien puestas.

**Comment by alvarag** [comment]
Antes de que lo vea Maudes y le de un _parranque_ te lo digo yo: una relación tiene que estar entre dos entidades. Puede haber más de una relación entre entidades pero en ningún caso una relación puede conectarse con otra relación. Por lo tanto: Asignatura -< tiene >- Grupos y esa relación tiene (agregación entre entidades) es la que se relaciona con curso académico  mediante pertenece

**Comment by alvarag** [comment]
Otro detalle menor, la cardinalidad de área-dpto: un área en un dpto y un dpto varias áreas

**Comment by idg0015** [comment]
Creo que ya está corregido:
![Diagrama E-R Bien](https://user-images.githubusercontent.com/74196389/223994060-459bf9e5-3cf0-4db7-b443-d28eaa1e5ecd.jpg)

La cardinalidad de área-dpto la tenía como dices en un principio, pero en el borrador de la reunión ponía que existen áreas que están en varios departamentos, por eso lo cambié. Lo vuelvo a poner como estaba en un principio.

**Comment by alvarag** [comment]
Es que en verdad hay áreas en varios dptos (en la unI), pero dijimos que para simplificar aunque un área pueda exisitir con el mismo nombre en dos dptos: lo consideraremos áreas distintas.

En cuanto a la agregación todavía no esta bien, recuerda: una relación/agregación tiene que ir conectada a dos entidades. Y luego es esa agregación la que se relacionará con una entidad con otra relación. Ten en cuenta que una agregación no deja de ser una relación entre dos entidades que una vez se consideran juntas (mediante dicha relación) actúan como una entidad nueva.

En resumen:
- Asignatura "se imparte" en un curso académico. Esta es la relación que se agrega (con cuadradito). 
- La relación "asignatura se imparte en curso académico " es la que se relaciona con Grupo, "tiene". Hablando con Jesús (ahora mismo por videoconferencia) le planteaba hacer que eso fuera otra agregación y le parece bien.
- De esta manera el "tiene" que te acabo de decir se relaciona con docente mediante "imparte"

Si no lo ves claro lo vemos por Teams en unmomento.

**Comment by idg0015** [comment]
Si lo podemos ver por Teams te lo agradezco, estoy conectado para cuando puedas llamarme.

**Comment by alvarag** [comment]
Mucho mejor, creo que ha habido un cambio de una cardinalidad de la versión previa a esta: un profesor podría tener varias plazas. Ejemplos:
- Imagina un Profesor asociado para el primer cuatrimestre que firm un nuevo contrato para el segundo cuatrimestre.
- Un ayudante doctor que se le acabe el contrato (ej. lectura de tesis) y luego empiece con un contrato de investigador
- ...

**Comment by idg0015** [comment]
Añado el diagrama con esos cambios. De momento he puesto los dos campos de año inicio y fin hasta ver como lo resolvemos.
![Diagrama E-R Bien](https://user-images.githubusercontent.com/74196389/224564674-ab9033a2-c225-4144-913b-a60f4346b93e.jpg)

**Comment by alvarag** [comment]
Algunos comentarios:
- Recuerdo que me dijiste que el cuadrado te lo ponía encima del rombo la aplicación, pero tal y como está perdemos la información de quién es la relación que forma la agregación. Por lo tanto hay que grandar un poco el rectángulo para que se pueda ver qué líneas llegan hasta el rombo y qué líneas llegn solo hasta el rectángulo.
- Vamos a hacer que la relación imparte vaya directamente a plaza y es plaza la que es ocupada por un docente.
- Comentar con Carlos si un grupo es solo para una asignatura o si un grupo esta en varias asignaturas

**Comment by idg0015** [comment]
![Diagrama E-R Bien](https://user-images.githubusercontent.com/74196389/224666622-f19d9074-65d2-4f85-ac02-f0eded480311.jpg)

**Comment by idg0015** [comment]
Dejo el último diagrama y cierro la issue

![Diagrama E-R Bien](https://user-images.githubusercontent.com/74196389/224957871-84f67789-c270-4db9-be8c-addbb2e45c3e.jpg)
