### ISSUE TITLE
Cambios en la documentación

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#22]

**Comment by idg0015** [comment]
Perfecto, entendido. Es que se me hacía raro que al visualizar el PDF la imagen quedase en medio de otro texto, pero si es así como debe estar lo cambio.

**Comment by alvarag** [comment]
Exacto, tal y como te comenta Carlos la idea es que LaTeX sea el encargado de decidir dónde colocar cada una de las figuras. Él dispone de algoritmos de diseño que considera cómo y dónde colocar las imágenes para que queden mejor (aunque nos pueda parecer raro en ocasiones).

Un comentario menor, pero que es interesante que sepas. Para evitar que la referencia (el numerito) se te descuelgue de su texto en vez de:

```latex
...como se observa en la figura \ref{labelFigura}...
```

Utiliza la virgulilla en vez del espacio. Esto hace un espacio no separable y evita que el  número se pueda ir a otra línea.

```latex
...como se observa en la figura~\ref{labelFigura}...
```

Saludos,

**Comment by idg0015** [comment]
De acuerdo, lo pongo de esa manera.
Muchas gracias.
