### ISSUE TITLE
Programar el apartado de gestión de cursos en la web

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#33]
Este apartado supone la creación, modificación, duplicación y eliminación de cursos.

**Comment by idg0015** [comment]
@carlospardoaguilar @alvarag 
Tengo una duda con los códigos de los grupos. Creo que van así:
- Presencial:
  - Teóricos: 1, 2, .... 
  - Prácticos: 101, 102,.... 201,202,....
- Inglés:
   - Teóricos: 80, 81, .... 
  - Prácticos: 801, 802,.... 811, 812,....
- Online:
   - Teóricos: 90, 91, .... 
  - Prácticos: 901, 902,.... 911, 912,....

¿Es esto correcto?

**Comment by alvarag** [comment]
Yo creo que también, pero seguro que Carlos lo tiene más claro.

**Comment by carlospardoaguilar** [comment]
Sí




Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: Ignacio Dávila ***@***.***>
Enviado: jueves, 11 de mayo de 2023 19:30
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Cc: CARLOS PARDO AGUILAR ***@***.***>; Mention ***@***.***>
Asunto: Re: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Programar el apartado de gestión de cursos en la web (Issue #33)


@carlospardoaguilar<https://github.com/carlospardoaguilar> @alvarag<https://github.com/alvarag>
Tengo una duda con los códigos de los grupos. Creo que van así:

  *   Presencial:
     *   Teóricos: 1, 2, ....
     *   Prácticos: 101, 102,.... 201,202,....
  *   Inglés:
     *   Teóricos: 80, 81, ....
     *   Prácticos: 801, 802,.... 811, 812,....
  *   Online:
     *   Teóricos: 90, 91, ....
     *   Prácticos: 901, 902,.... 911, 912,....

¿Es esto correcto?

**Comment by idg0015** [comment]
Perfecto, gracias.
