### ISSUE TITLE
Avanzar en la memoria

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#39]

**Comment by alvarag** [comment]
Algunos comentarios para avanzar

[memoria-AAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11509139/memoria-AAG.pdf)
[anexos-AAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11509141/anexos-AAG.pdf)

**Comment by idg0015** [comment]
Perfecto, gracias!

**Comment by alvarag** [comment]
Puedes probar a usar ```\usepackage{pdflscape}``` en vez de ```\usepackage{lscape}``` que creo es el paquete que rota la página en el pdf para visualizarlo mejor en el PC
