### ISSUE TITLE
Creación de casos de uso junto a su vista del diagrama E/R

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#4]
Se pretende crear los casos de uso vistos en la reunión semanal además de su vista del diagrama E/R y un boceto de la interfaz de la aplicación para cada caso de uso.

**Comment by alvarag** [comment]
La próxima semana le damos un repaso a los casos de uso y al diagrama. Entiendo que añadir un docente podría incluir asignar horas a un docente 

Asociar plaza a un docente podría incluirse en mantenimiento de docente y plazas

**Comment by idg0015** [comment]
Dejo aquí los E/R y vistas de los 3 casos de uso que vimos que son los que están causando más problemas:
- CU 6.1 Añadir un curso académico
![ER CU6 1 bien](https://user-images.githubusercontent.com/74196389/224565247-254f3915-13c6-4efd-a8fe-e56c865b0e9d.jpg)
![creacin_de_cursos](https://user-images.githubusercontent.com/74196389/224565526-aeb05ec2-17b7-45cf-a3b3-ad954ffa4fce.png)


- CU 11 Asignar horas a un docente en un grupo durante un curso
![ER CU11](https://user-images.githubusercontent.com/74196389/224565330-2cc8a212-94f4-4fcd-a6b1-4498dd1fc8b0.jpg)
![asignar_horas_grupo_docente](https://user-images.githubusercontent.com/74196389/224565582-b33473c4-85ac-4bc3-a529-6be68e44be77.png)
De la vista anterior se pasaría a esta:
![asignar_horas_grupo_docente_2](https://user-images.githubusercontent.com/74196389/224565586-8551c3bd-8a68-4aa8-824c-1929ec317ca0.png)


- CU 12 Asociar plaza a un docente
![ER CU12](https://user-images.githubusercontent.com/74196389/224565340-32cc2dd5-3c5a-4e2a-92c8-5572cadecdcb.jpg)
![asignar_plaza_a_docente](https://user-images.githubusercontent.com/74196389/224565589-47cfb341-f44d-4233-b4b2-5cee642d2f2e.png)

En el caso de querer desvincular la plaza a un docente, la vista podría ser algo de este estilo:
![desvincular_plaza_a_docente](https://user-images.githubusercontent.com/74196389/224565661-f39ea010-a7c0-4dae-a07a-1ab73fc53015.png)
