### ISSUE TITLE
No aparecen departamentos en creación de área

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#46]
He creado un dpto:

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/035b811a-d419-4a02-86e8-645fbbf41155)

Pero no aparece en el selector al crear área:

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/1ad2bf8a-3fb0-4a6d-8462-7d21be219e9b)

**Comment by alvarag** [comment]
Ocurre lo mismo cuando trato de añadir una plaza, no me aparece ningún docente en el desplegable.

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/2a94b4ce-2079-4e17-8e2c-377c1fcef639)

**Comment by idg0015** [comment]
En los selectores que no aparecen datos de primeras es porque se obtienen los datos realizando una búsqueda de lo que se escribe en el campo de texto del selector mediante una solicitud ajax para no cargar toda la información de golpe. Según se escribe van apareciendo las opciones que concuerdan.
Los selectores que sí tienen las opciones de primeras son aquellos en los que debería haber menos opciones y entonces no hay problema con que estas esten precargadas.
