### ISSUE TITLE
Campos obligatorios en "Añadir plaza"

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#48]
Buenos días @carlospardoaguilar ,

En la pantalla de "Añadir plaza" ahora mismo todos los campos son obligatorios, pero entiendo que no siempre es así, ¿no? Por ejemplo un docente que lleva toda la vida en la uni tiene sentido informar plaza RPT?

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/3d53a84e-3fbe-4636-bd18-0c258febb25f)

Gracias Carlos

**Comment by alvarag** [comment]
@idg0015 una cosa es segura, la fecha de cese no es obligatoria puesto que solo se informa si ha finalizado dicha plaza

**Comment by carlospardoaguilar** [comment]
si puede ser interesante tener la información de la plaza de RPT, sale en algunos listados y no nos acordamos de cual es cada una

**Comment by alvarag** [comment]
¿Y el número de concurso también?

**Comment by alvarag** [comment]
No tenemos en ningún sitio almacenado si es laboral o no la plaza... ¿la creamos como campo nuevo? O mejor dejamos como opcional el campo de concurso y que sea el usuario el que la rellene cuando toque?

**Comment by carlospardoaguilar** [comment]
déjalo opcional

**Comment by idg0015** [comment]
Ya he hecho estos cambios y están subidos. Dejo de momento la issue abierta hasta ver si está todo bien.
