### ISSUE TITLE
Crear carga masiva de datos

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#49]
Apunto como tarea nuestra la de crear una hoja de cálculo con los datos de asignaturas, docentes, áreas, dptos... que le puedan servir a @idg0015 para alimentar su script y tener unos datos con los que probar la aplicación y funcionaliad completa.

**Comment by idg0015** [comment]
En cuanto pueda lo miro.
