### ISSUE TITLE
Curso duplicado

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#50]
Permite crear un curso con el mismo año de inicio que otro ya existente:

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/e7861412-c294-4bc7-8d08-bc74e3a62dee)

**Comment by idg0015** [comment]
Solucionado
