### ISSUE TITLE
Dos plazas con el mismo docente

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#51]
En caso de que un docente ya tenga una plaza asignada y NO tenga fecha de fin: a ese docente no puede asignársele una nueva plaza.

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/83953d60-9c5e-4e0c-9a0c-267117462d11)

**Comment by idg0015** [comment]
Solucionado, ¿se debería hacer alguna comprobación de la fecha de cese con la fecha actual? ¿O si tiene fecha de cese, debería permitir añadir una nueva plaza, sea cual sea la fecha?
