### ISSUE TITLE
Creación de opción para importar y exportar la base de datos

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#59]

**Comment by alvarag** [comment]
Sí, la idea es exportar los datos. La estructura entiendo que viene ya "montada" con la aplicación web y por lo tanto no sería necesario.

Mi idea es un exportar que te saque todos los datos a un fichero y que luego al importar puedas meter todo eso en una instalación limpia

**Comment by idg0015** [comment]
Vale perfecto. Sí, la estructura se crea al desplegar la aplicación.
