### ISSUE TITLE
Avanzar documentación

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#60]

**Comment by alvarag** [comment]
Comentarios sobre la documentación, tenemos un problema con las referencias: luego lo comentamos.

[anexosAAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725575/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725576/memoriaAAG.pdf)

**Comment by carlospardoaguilar** [comment]
yo quitaría las negritas de la primera columna de todos los requisitos y usaría un tipo de letra menor para «Versión»,«Autor», que para «1.0»,«Ignacio ...»,
Los apartados no son importantes, están repetidos en todas las tablas, lo importante es lo que se dice a la derecha


Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: Álvar Arnaiz-González ***@***.***>
Enviado: lunes, 12 de junio de 2023 18:19
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Avanzar documentación (Issue #60)


Comentarios sobre la documentación, tenemos un problema con las referencias: luego lo comentamos.

anexosAAG.pdf<https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725575/anexosAAG.pdf>
memoriaAAG.pdf<https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725576/memoriaAAG.pdf>

**Comment by carlospardoaguilar** [comment]
No girar la página 70 de los anexos, girar solo la imagen no el captión
idem pág 72


Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: CARLOS PARDO AGUILAR ***@***.***>
Enviado: lunes, 12 de junio de 2023 18:27
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Asunto: RE: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Avanzar documentación (Issue #60)

yo quitaría las negritas de la primera columna de todos los requisitos y usaría un tipo de letra menor para «Versión»,«Autor», que para «1.0»,«Ignacio ...»,
Los apartados no son importantes, están repetidos en todas las tablas, lo importante es lo que se dice a la derecha


Reciba un saludo de
- - -[Vista previa de imagen]
Dr.D. Carlos Pardo Aguilar (LSI<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros>,<https://www.ubu.es/departamento-de-ingenieria-civil/departamento-de-ingenieria-civil/area-de-lenguajes-y-sistemas-informaticos/miembros> ADMIRABLE<http://wwww.ubu.es/advanced-data-mining-research-and-bioinformatics-learning-admirable>, DIGIT<http://wwww.ubu.es/formacion-e-innovacion-educativa/grupos-de-innovacion-docente-de-la-universidad-de-burgos/gid-de-la-ubu-digit-docencia-de-informatica-en-grados-de-ingenieria-y-trabajos-fin-de>)
Escuela Politécnica Superior<http://www.ubu.es/eps>, despacho DE28, edificio Milanera
       C/ Villadiego s/n
        09001 Burgos
https://twitter.com/CPardoAg/status/743102105800593408
- - -

Vocal, representante de Burgos, en la Junta de Gobierno del CPIICyL

________________________________
De: Álvar Arnaiz-González ***@***.***>
Enviado: lunes, 12 de junio de 2023 18:19
Para: idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU] Avanzar documentación (Issue #60)


Comentarios sobre la documentación, tenemos un problema con las referencias: luego lo comentamos.

anexosAAG.pdf<https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725575/anexosAAG.pdf>
memoriaAAG.pdf<https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11725576/memoriaAAG.pdf>

**Comment by carlospardoaguilar** [comment]
Centra todas las tablas de descripción de las tablas de la BD
