### ISSUE TITLE
Añadir documentación y solucionar errores vistos

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#63]

**Comment by idg0015** [comment]
@carlospardoaguilar @alvarag Estoy teniendo un problema con unas referencias en Latex.
Me aparece el mismo nombre en todas estas referencias, aunque si apuntan bien si pulsas sobre ellas:
![Captura](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/74196389/89dc8c6f-4e44-436e-8ba9-bad2b443df2a)


En Latex está así:

![Captura2](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/74196389/a534fbe6-08f5-41d0-bdd8-51f9d263ad5c)

Y en cada tabla está el correspondiente label con el mismo nombre.

¿Sabéis por qué puede ser?. 
Gracias de antemano.

**Comment by carlospardoaguilar** [comment]
Quita los puntos del los labels

creo que han de ser identificadores y el punto no suele ser válido en ningún lenguaje dentro de un identificador

puede sustituirlos por el guion bajo "_"

No Message ID: ***@***.***>

**Comment by alvarag** [comment]
Sí, como bien dice Carlos no le gustan los puntos en las referencias

**Comment by idg0015** [comment]
Muchas gracias, era eso.
