### ISSUE TITLE
Indicar por qué campo se va a buscar

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#67]
En las pantallas no es evidente qué campo está utilizando para la búsqueda, igual sería bueno indicarlo para evitar confusiones:

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/706f950e-c4f4-4156-997a-dc638babe15c)

**Comment by idg0015** [comment]
La búsqueda se realiza en todos los campos, lo que significa que puedes escribir el nombre, tipo, titulación, etc., y se filtrarán las palabras detectadas, sin importar el campo al que pertenezcan.
Lo he estado probando y parece funcionar bien, no sé si fue un error y por eso no aparecían, pero no consigo que falle.

**Comment by alvarag** [comment]
¿Puede ser por mayúsculas minúsculas?

**Comment by idg0015** [comment]
No, no distingue entre mayúsculas y minúsculas. De hecho he realizado la misma búsqueda en distintos navegadires y si que me aparecen bien:
![Captura](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/74196389/ebd323e9-8dd2-4cb9-98b9-5456673d47d6)
