### ISSUE TITLE
Añadir documentación en los anexos

### ISSUE THREAD

**Issue by idg0015** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#73]

**Comment by alvarag** [comment]
Comentarios en memoria y anexos

[anexosAAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11870377/anexosAAG.pdf)
[memoriaAAG.pdf](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/files/11870378/memoriaAAG.pdf)
