### ISSUE TITLE
Mantenimiento Horas/Grupo

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#80]
Buenas tardes,

Propongo un par de cambios en cuanto al mantenimiento de horas/grupo.

- En la cabecera es un poco confuso el "horas" y "horas asignadas". Entiendo que la primera es "horas en grupo" y la otra "horas totales asignadas" o algo similar. Es que sino confunde creo.

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/85113b10-b530-4a0c-a2ec-2c31062735c9)

- En el título, una vez pinchas en "Asignación docente" luego cursos es claro, grupos y horas no queda bien... propongo: "horas/grupo" o algo similar y en grupos "grupos/asignatura" para que quede claro qué se va  a hacer en cada pantalla.

![imagen](https://github.com/idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU/assets/9881614/83ed1c0c-25ff-486d-b537-e1044d9973bd)

**Comment by idg0015** [comment]
> Cuando modifico las horas, me escribe de izquierda a derecha... no sé si será por alguna configuración extraña mía o a ti también te sucede:
> 
> ![imagen](https://user-images.githubusercontent.com/9881614/249539525-ff4a9f00-b585-4108-ae63-d7017af37d21.png)
> 
> Quería poner 10 pero me ha hecho 01 porque tras escribir el 1 me ha puesto el cursor a la izquierda del número recién introducido

Lo he estado revisando y he visto que fallaba en algunos navegadores. Era problema de que, al usar una expresión regular para permitir solo números, en algunos navegadores reseteaba la posición del cursor.
Lo he solucionando guardando la posición del cursor y devolviéndolo a su lugar después de pasar la expresión regular.

Cuando tenga otros cambios que estoy haciendo lo subo a Heroku.
