### ISSUE TITLE
Mejorar README con Linux

### ISSUE THREAD

**Issue by alvarag** [idg0015/Aplicacion-de-gestion-del-PDI-de-un-area-de-la-UBU#83]
Estaría bien que los comandos que indicas fuesen tanto para Windows como para Linux. Si no me equivoco solo tendrías que cambiar/añadir en este paso:
```
env\Scripts\activate.bat
```

El resto son iguales (creo)

**Comment by idg0015** [comment]
¿Debo entregar o subir los videos a GitHub, o es suficiente con tenerlos en OneDrive?

**Comment by alvarag** [comment]
Puedes dejarlos en OneDrive/Youtube para enlazarlos desde el repo, pero en los USBs que entregues es conveniente que también estén.

**Comment by alvarag** [comment]
Corrige en el README:
"Repositório" -> "Repositorio"

**Comment by idg0015** [comment]
Vale, prefecto. Gracias!
